// import webpack from 'webpack';
// import ExtractTextPlugin from "extract-text-webpack-plugin";


const webpack = require('webpack')
const CleanWebpackPlugin = require('clean-webpack-plugin')

const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const path = require('path');
const htmlPlugin = require('html-loader');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
// const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
	context: path.resolve(__dirname, "src"),
	entry: {
		"main": path.resolve('./src/entry.js')
	},
	output: {
		path: path.resolve(__dirname, 'dist'),
		pathinfo: true,
		filename: "[name]-bundle-[hash].js",
		publicPath: './'
	},
	module: {
		rules: [
			{
				test: /\.(woff|woff2|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
				loader: 'file-loader?&name=assets/fonts/[name].[hash].[ext]'
			}, {
				// ASSET LOADER
				// Reference: https://github.com/webpack/file-loader
				// Copy png, jpg, jpeg, gif, svg, woff, woff2, ttf, eot files to output
				// Rename the file using the asset hash
				// Pass along the updated reference to your code
				// You can add here any file extension you want to get copied to your output
				// |woff|woff2|ttf|eot
				test: /\.(png|jpg|jpeg|gif|svg)(\?v=\d+\.\d+\.\d+)?$/,
				// loader: 'file-loader'
				loader: 'url-loader?limit=8192&name=assets/img/[name].[hash].[ext]'
			}, {
				test: /\.css$/,
				loader: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: [
						{
							loader: "css-loader",
							options: {
								minimize: true,
								sourceMap: true
							}
						}
					]
				})
			}, {
				test: /\.html$/,
				// use: [ 'file-loader?name=[path][name].[ext]!extract-loader!html-loader' ]
				use: [
					{
						loader: 'html-loader?attrs=false',
						options: {
							minimize: true,
							removeComments: true,
							collapseWhitespace: true
						}
					}
				]
			}
		]
	},
	resolve: {
		extensions: [
			'.js', '.css'
		],
		alias: {
			js: path.join(__dirname, "./src/js"),
			css: path.join(__dirname, "./src/css")
		}
	},
	plugins: [
		new CleanWebpackPlugin('dist'),
		new webpack.ProvidePlugin({$: "jquery", jQuery: "jquery"}),
		new ExtractTextPlugin("stylesheet.css"),
		new OptimizeCssAssetsPlugin({
      cssProcessor: require('cssnano'),
      cssProcessorOptions: { discardComments: {removeAll: true } },
      canPrint: true
    }),
		new webpack.optimize.UglifyJsPlugin({compress: true,comments:false}),
		new webpack.BannerPlugin({banner: "auto-generated by webpack"}),
		new HtmlWebpackPlugin({title: '健育儿', template: 'template.html', minify: false})
	],
	performance: {
		hints: "warning"
	}
};
